name: Build

on:
  push:

jobs:
  Git:
    name: Git
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit Lint
        uses: webiny/action-conventional-commits@v1.1.0
      - name: Secrets Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Shell Lint
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Outstanding Todos
        run: |
          echo Checking for outstanding todos...
          TODO_COUNT=$(grep -r '[\/\/#] [Tt][Oo][Dd][Oo]' --exclude-dir .git . | wc -l)
          if [[ $TODO_COUNT -gt 0 ]] ; then
            echo "$TODO_COUNT" todos found...
            grep -r '[\/\/#] [Tt][Oo][Dd][Oo]' . 
            exit 1
          fi
          echo No todos found...


  Node:
    name: Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 16.x ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Unit Tests
        run: npm test
      - name: Test Coverage
        run: npm run test:coverage
      - name: Audit Dependencies
        run: npx better-npm-audit audit --level=high
      - name: Outdated Dependencies
        run: npx check-outdated --columns package,current,latest,wanted
